require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnemiesController do

  # This should return the minimal set of attributes required to create a valid
  # Enemy. As you add validations to Enemy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all enemies as @enemies" do
      enemy = Enemy.create! valid_attributes
      get :index
      assigns(:enemies).should eq([enemy])
    end
  end

  describe "GET show" do
    it "assigns the requested enemy as @enemy" do
      enemy = Enemy.create! valid_attributes
      get :show, :id => enemy.id.to_s
      assigns(:enemy).should eq(enemy)
    end
  end

  describe "GET new" do
    it "assigns a new enemy as @enemy" do
      get :new
      assigns(:enemy).should be_a_new(Enemy)
    end
  end

  describe "GET edit" do
    it "assigns the requested enemy as @enemy" do
      enemy = Enemy.create! valid_attributes
      get :edit, :id => enemy.id.to_s
      assigns(:enemy).should eq(enemy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Enemy" do
        expect {
          post :create, :enemy => valid_attributes
        }.to change(Enemy, :count).by(1)
      end

      it "assigns a newly created enemy as @enemy" do
        post :create, :enemy => valid_attributes
        assigns(:enemy).should be_a(Enemy)
        assigns(:enemy).should be_persisted
      end

      it "redirects to the created enemy" do
        post :create, :enemy => valid_attributes
        response.should redirect_to(Enemy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enemy as @enemy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enemy.any_instance.stub(:save).and_return(false)
        post :create, :enemy => {}
        assigns(:enemy).should be_a_new(Enemy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enemy.any_instance.stub(:save).and_return(false)
        post :create, :enemy => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enemy" do
        enemy = Enemy.create! valid_attributes
        # Assuming there are no other enemies in the database, this
        # specifies that the Enemy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Enemy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => enemy.id, :enemy => {'these' => 'params'}
      end

      it "assigns the requested enemy as @enemy" do
        enemy = Enemy.create! valid_attributes
        put :update, :id => enemy.id, :enemy => valid_attributes
        assigns(:enemy).should eq(enemy)
      end

      it "redirects to the enemy" do
        enemy = Enemy.create! valid_attributes
        put :update, :id => enemy.id, :enemy => valid_attributes
        response.should redirect_to(enemy)
      end
    end

    describe "with invalid params" do
      it "assigns the enemy as @enemy" do
        enemy = Enemy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enemy.any_instance.stub(:save).and_return(false)
        put :update, :id => enemy.id.to_s, :enemy => {}
        assigns(:enemy).should eq(enemy)
      end

      it "re-renders the 'edit' template" do
        enemy = Enemy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enemy.any_instance.stub(:save).and_return(false)
        put :update, :id => enemy.id.to_s, :enemy => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enemy" do
      enemy = Enemy.create! valid_attributes
      expect {
        delete :destroy, :id => enemy.id.to_s
      }.to change(Enemy, :count).by(-1)
    end

    it "redirects to the enemies list" do
      enemy = Enemy.create! valid_attributes
      delete :destroy, :id => enemy.id.to_s
      response.should redirect_to(enemies_url)
    end
  end

end
